/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;
import Clases.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.util.List;



/**
 *
 * @author omargarcia
 */
public class Problema4 extends javax.swing.JFrame {

    /**
     * Creates new form Problema4
     */
    public Problema4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INSERTAR = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        insertarusuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mostrarInsertar = new javax.swing.JButton();
        mostrarregistros = new javax.swing.JButton();
        mostrarBuscar = new javax.swing.JButton();
        mostrarValidar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablausuarios = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        INSERTAR.setTitle("Insertar");
        INSERTAR.setBounds(new java.awt.Rectangle(0, 0, 450, 350));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Correo:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        insertarusuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertarusuario.setText("INSERTAR");
        insertarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarusuarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel1.setText("Insertar User");

        javax.swing.GroupLayout INSERTARLayout = new javax.swing.GroupLayout(INSERTAR.getContentPane());
        INSERTAR.getContentPane().setLayout(INSERTARLayout);
        INSERTARLayout.setHorizontalGroup(
            INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INSERTARLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INSERTARLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INSERTARLayout.createSequentialGroup()
                        .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INSERTARLayout.createSequentialGroup()
                                .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INSERTARLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(INSERTARLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(INSERTARLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(insertarusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel2)
                .addGap(153, 153, 153))
        );
        INSERTARLayout.setVerticalGroup(
            INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INSERTARLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INSERTARLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(INSERTARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(insertarusuario)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mostrarInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarInsertar.setText("INSERTAR");
        mostrarInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarInsertarActionPerformed(evt);
            }
        });

        mostrarregistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarregistros.setText("MOSTRAR");
        mostrarregistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarregistrosActionPerformed(evt);
            }
        });

        mostrarBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarBuscar.setText("BUSCAR");
        mostrarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBuscarActionPerformed(evt);
            }
        });

        mostrarValidar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarValidar.setText("VALIDAR");
        mostrarValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarValidarActionPerformed(evt);
            }
        });

        tablausuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablausuarios);

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel7.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabel7)
                                .addGap(73, 73, 73))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mostrarInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mostrarregistros)
                                .addGap(18, 18, 18)
                                .addComponent(mostrarBuscar)
                                .addGap(32, 32, 32)))
                        .addComponent(mostrarValidar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarInsertar)
                    .addComponent(mostrarregistros)
                    .addComponent(mostrarBuscar)
                    .addComponent(mostrarValidar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void limpiarCampos() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }
    private void mostrarregistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarregistrosActionPerformed
        // TODO add your handling code here:
    try {
        List<Usuario> usuarios = Usuario.mostrar_todos();
        DefaultTableModel model = (DefaultTableModel) tablausuarios.getModel();
        model.setRowCount(0); // Limpiar filas existentes
        
        for (Usuario usuario : usuarios) {
            model.addRow(new Object[]{usuario.getUsuario(), usuario.getNombre(), usuario.getCorreo()});
        }
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_mostrarregistrosActionPerformed

    private void mostrarInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarInsertarActionPerformed
        // TODO add your handling code here:
        INSERTAR.setVisible(true);
    }//GEN-LAST:event_mostrarInsertarActionPerformed

    private void mostrarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBuscarActionPerformed
        // TODO add your handling code here:
    String usuario = JOptionPane.showInputDialog(this, "Ingrese el usuario a buscar:");
    if (usuario != null && !usuario.isEmpty()) {
        try {
            Usuario usuarioEncontrado = Usuario.buscar(usuario);
            DefaultTableModel model = (DefaultTableModel) tablausuarios.getModel();
            model.setRowCount(0); // Limpiar filas existentes
            
            if (usuarioEncontrado != null) {
                model.addRow(new Object[]{usuarioEncontrado.getUsuario(), usuarioEncontrado.getNombre(), usuarioEncontrado.getCorreo()});
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado", "Resultado de Búsqueda", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_mostrarBuscarActionPerformed

    private void mostrarValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarValidarActionPerformed
        // TODO add your handling code here:
                String usuario = JOptionPane.showInputDialog(this, "Ingrese el usuario:");
        String password = JOptionPane.showInputDialog(this, "Ingrese la contraseña:");
        if (usuario != null && !usuario.isEmpty() && password != null && !password.isEmpty()) {
            try {
                boolean valido = Usuario.validar_usuario(usuario, password);
                if (valido) {
                    JOptionPane.showMessageDialog(this, "Usuario y contraseña válidos", "Validación", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Validación", JOptionPane.WARNING_MESSAGE);
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_mostrarValidarActionPerformed

    private void insertarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarusuarioActionPerformed
        // TODO add your handling code here:
                String usuario = jTextField1.getText();
        String password = jTextField2.getText();
        String nombre = jTextField3.getText();
        String correo = jTextField4.getText();
        
        if (!usuario.isEmpty() && !password.isEmpty() && !nombre.isEmpty() && !correo.isEmpty()) {
            Usuario nuevoUsuario = new Usuario(usuario, password, nombre, correo);
            try {
                nuevoUsuario.insertar();
                JOptionPane.showMessageDialog(this, "Usuario insertado correctamente", "Inserción", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al escribir en el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_insertarusuarioActionPerformed

        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame INSERTAR;
    private javax.swing.JButton insertarusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton mostrarBuscar;
    private javax.swing.JButton mostrarInsertar;
    private javax.swing.JButton mostrarValidar;
    private javax.swing.JButton mostrarregistros;
    private javax.swing.JTable tablausuarios;
    // End of variables declaration//GEN-END:variables
}
